# development:
#   host: dev.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>

development:
  host: localhost:3000
  handle: wooden-meadow-4163
  email: cedric.lor@gmail.com
  api_key: 30520fc484fc9f6139f0ce15b588ca6f63ec9f0d
